# Generated by Django 3.1.4 on 2020-12-30 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('community', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storylike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.story'),
        ),
        migrations.AddField(
            model_name='storycomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='story',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.course'),
        ),
        migrations.AddField(
            model_name='story',
            name='liker',
            field=models.ManyToManyField(related_name='liked_stories', through='community.StoryLike', to='user.User'),
        ),
        migrations.AddField(
            model_name='story',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='coursecommunitylike',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.coursecommunity'),
        ),
        migrations.AddField(
            model_name='coursecommunitylike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='coursecommunitycomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.coursecommunity'),
        ),
        migrations.AddField(
            model_name='coursecommunitycomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='coursecommunity',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.course'),
        ),
        migrations.AddField(
            model_name='coursecommunity',
            name='liker',
            field=models.ManyToManyField(related_name='liked_communities', through='community.CourseCommunityLike', to='user.User'),
        ),
        migrations.AddField(
            model_name='coursecommunity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
