# Generated by Django 3.1.4 on 2020-12-30 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0002_auto_20201230_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cover_photo', models.URLField()),
                ('thumbnail', models.URLField()),
                ('creator_description', models.CharField(max_length=150)),
                ('summary_photo', models.URLField()),
                ('specific_category', models.CharField(max_length=150)),
                ('expiry_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.course')),
                ('liker', models.ManyToManyField(related_name='liked_requests', to='user.User')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory')),
            ],
            options={
                'db_table': 'course_requests',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.courserequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'supports',
            },
        ),
        migrations.CreateModel(
            name='RequestCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.courserequest')),
                ('voter', models.ManyToManyField(related_name='request_votes', to='user.User')),
            ],
            options={
                'db_table': 'request_curriculums',
            },
        ),
        migrations.CreateModel(
            name='RequestCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField()),
                ('description', models.CharField(max_length=150)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.courserequest')),
            ],
            options={
                'db_table': 'request_cards',
            },
        ),
        migrations.AddField(
            model_name='courserequest',
            name='tag',
            field=models.ManyToManyField(to='request.Tag'),
        ),
    ]
