# Generated by Django 3.1.4 on 2021-01-05 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'course_curriculums',
            },
        ),
        migrations.CreateModel(
            name='CourseSubCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('order', models.IntegerField()),
                ('video', models.URLField()),
                ('note', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'course_sub_curriculums',
            },
        ),
        migrations.CreateModel(
            name='SubCurriculumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=150)),
                ('image_url', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sub_curriculum_comments',
            },
        ),
        migrations.CreateModel(
            name='SubCurriculumCommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=150)),
                ('image_url', models.URLField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subcurriculumcomment')),
            ],
            options={
                'db_table': 'sub_curriculum_comment_replies',
            },
        ),
    ]
